package com.jetski.shared.email;

/**
 * Service interface for sending emails.
 *
 * Different implementations based on Spring profile:
 * - local/dev: DevEmailService (logs to console/file)
 * - prod: SmtpEmailService (sends real emails)
 *
 * @author Jetski Team
 * @since 0.3.0
 */
public interface EmailService {

    /**
     * Send user invitation email with activation link and temporary password (Option 2 flow).
     *
     * This email invites a user to join the platform and includes:
     * - Activation link with token
     * - Temporary password (random, 12 chars)
     *
     * User will use both to activate account. On first login, Keycloak will
     * force password change via UPDATE_PASSWORD required action.
     *
     * @param to Recipient email address
     * @param name User's full name
     * @param activationLink Link to frontend activation page (e.g., http://localhost:3000/activate?token=xxx)
     * @param temporaryPassword Temporary password generated by backend (plain text, sent only in email)
     */
    void sendInvitationEmail(String to, String name, String activationLink, String temporaryPassword);

    /**
     * Send password reset email.
     *
     * @param to Recipient email address
     * @param name User's full name
     * @param resetLink Link to reset password
     */
    void sendPasswordResetEmail(String to, String name, String resetLink);
}
