package com.jetski.shared.email;

/**
 * Service interface for sending emails.
 *
 * Different implementations based on Spring profile:
 * - local/dev: DevEmailService (logs to console/file)
 * - prod: SmtpEmailService (sends real emails)
 *
 * @author Jetski Team
 * @since 0.3.0
 */
public interface EmailService {

    /**
     * Send user invitation email with activation link and temporary password (Option 2 flow).
     *
     * This email invites a user to join the platform and includes:
     * - Activation link with token
     * - Temporary password (random, 12 chars)
     *
     * User will use both to activate account. On first login, Keycloak will
     * force password change via UPDATE_PASSWORD required action.
     *
     * @param to Recipient email address
     * @param name User's full name
     * @param activationLink Link to frontend activation page (e.g., http://localhost:3000/activate?token=xxx)
     * @param temporaryPassword Temporary password generated by backend (plain text, sent only in email)
     */
    void sendInvitationEmail(String to, String name, String activationLink, String temporaryPassword);

    /**
     * Convite de ativação da conta do CLIENTE (pré-conta criada no balcão — claim-token).
     *
     * <p>Mesma mecânica do convite de staff (link + senha temporária), mas com
     * template próprio: validade de 7 dias e texto do portal do cliente,
     * cobrindo também quem já tem conta no Meu Jet (a senha atual continua valendo).
     *
     * @param to Recipient email address
     * @param name Customer's full name
     * @param activationLink Link to portal activation page (e.g., https://host/portal/ativar?token=xxx)
     * @param temporaryPassword Temporary password generated by backend (plain text, sent only in email)
     */
    void sendClienteInvitationEmail(String to, String name, String activationLink, String temporaryPassword);

    /**
     * Send password reset email.
     *
     * @param to Recipient email address
     * @param name User's full name
     * @param resetLink Link to reset password
     */
    void sendPasswordResetEmail(String to, String name, String resetLink);

    /**
     * Envia um e-mail HTML com um anexo (ex.: o PDF consolidado de documentos).
     *
     * @param to destinatário
     * @param subject assunto
     * @param htmlBody corpo HTML
     * @param attachmentName nome do arquivo anexo (ex: documentos.pdf)
     * @param attachment conteúdo do anexo
     * @param attachmentContentType tipo MIME do anexo (ex: application/pdf)
     */
    default void sendEmailComAnexo(String to, String subject, String htmlBody,
                                   String attachmentName, byte[] attachment, String attachmentContentType) {
        sendEmailComAnexo(to, subject, htmlBody, attachmentName, attachment, attachmentContentType, null);
    }

    /**
     * Idem, com {@code Reply-To} opcional (ex.: o e-mail oficial do EAMA no ofício à
     * Capitania — NORMAM-212 item 5.4.2 — quando o "from" é o SMTP da plataforma).
     * O remetente é o tenant da sessão ({@link TenantSmtpResolver#forCurrentTenant()}).
     */
    default void sendEmailComAnexo(String to, String subject, String htmlBody,
                                   String attachmentName, byte[] attachment, String attachmentContentType,
                                   String replyTo) {
        sendEmailComAnexo(to, subject, htmlBody, attachmentName, attachment, attachmentContentType, replyTo, null);
    }

    /**
     * Identidade de remetente explícita, quando o e-mail deve sair em nome de um tenant
     * que NÃO é o da sessão. Caso de uso: o ofício à Capitania na emissão delegada — a
     * operadora dispara, mas o e-mail é da EAMA emissora (EMISSAO_DELEGADA_SPEC §8.J:
     * sem menção à operadora). Resolve o SMTP próprio de {@code tenantId}; sem SMTP
     * próprio, usa o global com {@code nome} como nome de exibição do "From".
     *
     * @param tenantId tenant cujo SMTP/identidade assina o e-mail
     * @param nome     nome de exibição quando cai no SMTP global (ex.: razão social)
     * @param copia    endereço em cópia (Cc) visível, opcional — ex.: a operadora
     *                 delegada acompanha o ofício que a EAMA remete em nome da parceria
     */
    record Remetente(java.util.UUID tenantId, String nome, String copia) {
        public Remetente(java.util.UUID tenantId, String nome) {
            this(tenantId, nome, null);
        }
    }

    /**
     * Idem, com remetente explícito. {@code remetente == null} equivale ao método de
     * 7 argumentos (remetente = tenant da sessão).
     */
    void sendEmailComAnexo(String to, String subject, String htmlBody,
                           String attachmentName, byte[] attachment, String attachmentContentType,
                           String replyTo, Remetente remetente);

    /**
     * Notifica um super admin de plataforma sobre uma nova empresa aguardando aprovação.
     *
     * @param to          email do super admin
     * @param razaoSocial razão social da empresa cadastrada
     * @param slug        identificador (slug) da empresa
     */
    void sendNewTenantNotification(String to, String razaoSocial, String slug);

    /**
     * Avisa um administrador da empresa sobre a mudança de status feita pela plataforma
     * (aprovada/suspensa/reativada). Best-effort — falha de envio nunca propaga.
     *
     * @param to          email do admin da empresa
     * @param acao        TENANT_APPROVED / TENANT_SUSPENDED / TENANT_REACTIVATED
     * @param razaoSocial razão social da empresa
     * @param motivo      motivo opcional (usado na suspensão; pode ser null)
     */
    void sendTenantStatusNotification(String to, String acao, String razaoSocial, String motivo);

    /**
     * Avisa um administrador da empresa que o período de teste está para vencer
     * (enviado em D-3 e D-1 pelo job de expiração). Best-effort.
     *
     * @param to            email do admin da empresa
     * @param razaoSocial   razão social da empresa
     * @param diasRestantes dias até o fim do trial (3 ou 1)
     * @param dataFim       data (dd/MM/yyyy) em que o trial vence
     */
    void sendTrialWarningNotification(String to, String razaoSocial, int diasRestantes, String dataFim);

    /** Envia um e-mail HTML simples (sem anexo). */
    void sendEmail(String to, String subject, String htmlBody);

    /**
     * Envia um e-mail HTML com uma imagem PNG embutida, referenciada no HTML por
     * {@code <img src="cid:contentId">} (ex.: QR Code do PIX). Best-effort, como
     * {@link #sendEmail}. Sem imagem, cai no envio simples.
     */
    default void sendEmailComImagemInline(String to, String subject, String htmlBody,
                                          String contentId, byte[] png) {
        sendEmail(to, subject, htmlBody);
    }
}
