# Docker Compose - Monitoring Stack for Jetski SaaS
# Full Observability Stack: Prometheus + Grafana + Loki + Promtail + Alertmanager + Jaeger
#
# Usage:
#   docker compose -f docker-compose-monitoring.yml up -d
#
# Access:
#   - Grafana: http://localhost:3000 (admin/admin)
#   - Prometheus: http://localhost:9090
#   - Loki: http://localhost:3100
#   - Alertmanager: http://localhost:9093
#   - Jaeger UI: http://localhost:16686
#   - Promtail: http://localhost:9080

services:
  # Prometheus - Metrics collection and storage
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: jetski-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Grafana - Visualization and dashboards
  grafana:
    image: grafana/grafana:10.1.5
    container_name: jetski-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki

  # Loki - Log aggregation
  loki:
    image: grafana/loki:2.9.2
    container_name: jetski-loki
    restart: unless-stopped
    user: root
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  # Promtail - Log shipping to Loki
  promtail:
    image: grafana/promtail:2.9.2
    container_name: jetski-promtail
    restart: unless-stopped
    ports:
      - "9080:9080"
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /tmp/backend-observability.log:/var/log/jetski/backend.log:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    depends_on:
      - loki

  # Alertmanager - Alert routing and notifications
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: jetski-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./monitoring/alertmanager/templates:/etc/alertmanager/templates:ro
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring

  # Jaeger - Distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:1.51
    container_name: jetski-jaeger
    restart: unless-stopped
    ports:
      - "5775:5775/udp"     # Zipkin compact thrift
      - "6831:6831/udp"     # Jaeger compact thrift
      - "6832:6832/udp"     # Jaeger binary thrift
      - "5778:5778"         # Config HTTP
      - "16686:16686"       # Jaeger UI
      - "14268:14268"       # Jaeger collector HTTP
      - "14250:14250"       # Jaeger gRPC
      - "9411:9411"         # Zipkin compatible endpoint
      - "4317:4317"         # OTLP gRPC
      - "4318:4318"         # OTLP HTTP
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoring

networks:
  monitoring:
    name: jetski-monitoring
    driver: bridge

volumes:
  prometheus-data:
    name: jetski-prometheus-data
  grafana-data:
    name: jetski-grafana-data
  loki-data:
    name: jetski-loki-data
  alertmanager-data:
    name: jetski-alertmanager-data
