# Promtail Configuration for Jetski SaaS
# Ships logs from backend application to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape backend application logs
  - job_name: jetski-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: jetski-backend
          application: jetski-api
          environment: local
          __path__: /var/log/jetski/*.log

    # Pipeline stages to parse and enrich logs
    pipeline_stages:
      # Parse JSON logs (for dev/production profiles)
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            logger: logger
            message: message
            correlation_id: correlation_id
            tenant_id: tenant_id
            trace_id: trace_id
            span_id: span_id

      # Extract correlation_id as label for easy filtering
      - labels:
          correlation_id:
          tenant_id:
          level:
          trace_id:

      # Add timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano

      # Output format for Loki
      - output:
          source: message

  # Scrape Docker container logs (alternative)
  - job_name: docker-jetski
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values:
              - "logging=promtail"

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'

    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            correlation_id: correlation_id
            tenant_id: tenant_id

      - labels:
          level:
          correlation_id:
          tenant_id:
