spring:
  datasource:
    url: jdbc:tc:postgresql:16:///test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    clean-disabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/jetski-saas
          jwk-set-uri: http://localhost:8080/realms/jetski-saas/protocol/openid-connect/certs

management:
  health:
    defaults:
      enabled: false  # Disable ALL health checks in tests
    db:
      enabled: false
    keycloak:
      enabled: false
    opa:
      enabled: false
    redis:
      enabled: false
    ldap:
      enabled: false
    mail:
      enabled: false
    diskspace:
      enabled: false
    ping:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    root: WARN
    com.jetski: DEBUG
    org.testcontainers: INFO
